INSERT INTO provincia (id, nombre, codigo) VALUES (1, 'Álava', 'VI');
INSERT INTO provincia (id, nombre, codigo) VALUES (2, 'Albacete', 'AB');
INSERT INTO provincia (id, nombre, codigo) VALUES (3, 'Alicante', 'A');
INSERT INTO provincia (id, nombre, codigo) VALUES (4, 'Almería', 'AL');
INSERT INTO provincia (id, nombre, codigo) VALUES (5, 'Asturias', 'O');
INSERT INTO provincia (id, nombre, codigo) VALUES (6, 'Ávila', 'AV');
INSERT INTO provincia (id, nombre, codigo) VALUES (7, 'Badajoz', 'BA');
INSERT INTO provincia (id, nombre, codigo) VALUES (8, 'Baleares', 'PM');
INSERT INTO provincia (id, nombre, codigo) VALUES (9, 'Barcelona', 'B');
INSERT INTO provincia (id, nombre, codigo) VALUES (10, 'Burgos', 'BU');
INSERT INTO provincia (id, nombre, codigo) VALUES (11, 'Cáceres', 'CC');
INSERT INTO provincia (id, nombre, codigo) VALUES (12, 'Cádiz', 'CA');
INSERT INTO provincia (id, nombre, codigo) VALUES (13, 'Cantabria', 'S');
INSERT INTO provincia (id, nombre, codigo) VALUES (14, 'Castellón', 'CS');
INSERT INTO provincia (id, nombre, codigo) VALUES (15, 'Ciudad Real', 'CR');
INSERT INTO provincia (id, nombre, codigo) VALUES (16, 'Córdoba', 'CO');
INSERT INTO provincia (id, nombre, codigo) VALUES (17, 'Cuenca', 'CU');
INSERT INTO provincia (id, nombre, codigo) VALUES (18, 'Girona', 'GI');
INSERT INTO provincia (id, nombre, codigo) VALUES (19, 'Granada', 'GR');
INSERT INTO provincia (id, nombre, codigo) VALUES (20, 'Guadalajara', 'GU');
INSERT INTO provincia (id, nombre, codigo) VALUES (21, 'Guipúzcoa', 'SS');
INSERT INTO provincia (id, nombre, codigo) VALUES (22, 'Huelva', 'H');
INSERT INTO provincia (id, nombre, codigo) VALUES (23, 'Huesca', 'HU');
INSERT INTO provincia (id, nombre, codigo) VALUES (24, 'Jaén', 'J');
INSERT INTO provincia (id, nombre, codigo) VALUES (25, 'La Coruña', 'C');
INSERT INTO provincia (id, nombre, codigo) VALUES (26, 'La Rioja', 'LO');
INSERT INTO provincia (id, nombre, codigo) VALUES (27, 'Las Palmas', 'GC');
INSERT INTO provincia (id, nombre, codigo) VALUES (28, 'León', 'LE');
INSERT INTO provincia (id, nombre, codigo) VALUES (29, 'Lleida', 'L');
INSERT INTO provincia (id, nombre, codigo) VALUES (30, 'Lugo', 'LU');
INSERT INTO provincia (id, nombre, codigo) VALUES (31, 'Madrid', 'M');
INSERT INTO provincia (id, nombre, codigo) VALUES (32, 'Málaga', 'MA');
INSERT INTO provincia (id, nombre, codigo) VALUES (33, 'Murcia', 'MU');
INSERT INTO provincia (id, nombre, codigo) VALUES (34, 'Navarra', 'NA');
INSERT INTO provincia (id, nombre, codigo) VALUES (35, 'Ourense', 'OR');
INSERT INTO provincia (id, nombre, codigo) VALUES (36, 'Palencia', 'P');
INSERT INTO provincia (id, nombre, codigo) VALUES (37, 'Pontevedra', 'PO');
INSERT INTO provincia (id, nombre, codigo) VALUES (38, 'Salamanca', 'SA');
INSERT INTO provincia (id, nombre, codigo) VALUES (39, 'Santa Cruz de Tenerife', 'TF');
INSERT INTO provincia (id, nombre, codigo) VALUES (40, 'Segovia', 'SG');
INSERT INTO provincia (id, nombre, codigo) VALUES (41, 'Sevilla', 'SE');
INSERT INTO provincia (id, nombre, codigo) VALUES (42, 'Soria', 'SO');
INSERT INTO provincia (id, nombre, codigo) VALUES (43, 'Tarragona', 'T');
INSERT INTO provincia (id, nombre, codigo) VALUES (44, 'Teruel', 'TE');
INSERT INTO provincia (id, nombre, codigo) VALUES (45, 'Toledo', 'TO');
INSERT INTO provincia (id, nombre, codigo) VALUES (46, 'Valencia', 'V');
INSERT INTO provincia (id, nombre, codigo) VALUES (47, 'Valladolid', 'VA');
INSERT INTO provincia (id, nombre, codigo) VALUES (48, 'Vizcaya', 'BI');
INSERT INTO provincia (id, nombre, codigo) VALUES (49, 'Zamora', 'ZA');
INSERT INTO provincia (id, nombre, codigo) VALUES (50, 'Zaragoza', 'Z');
INSERT INTO provincia (id, nombre, codigo) VALUES (51, 'Ceuta', 'CE');
INSERT INTO provincia (id, nombre, codigo) VALUES (52, 'Melilla', 'ML');