INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (1, 'Álava', 'VI', 'Provincia de Álava');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (2, 'Albacete', 'AB', 'Provincia de Albacete');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (3, 'Alicante', 'A', 'Provincia de Alicante');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (4, 'Almería', 'AL', 'Provincia de Almería');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (5, 'Asturias', 'O', 'Provincia de Asturias');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (6, 'Ávila', 'AV', 'Provincia de Ávila');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (7, 'Badajoz', 'BA', 'Provincia de Badajoz');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (8, 'Baleares', 'PM', 'Provincia de Baleares');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (9, 'Barcelona', 'B', 'Provincia de Barcelona');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (10, 'Burgos', 'BU', 'Provincia de Burgos');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (11, 'Cáceres', 'CC', 'Provincia de Cáceres');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (12, 'Cádiz', 'CA', 'Provincia de Cádiz');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (13, 'Cantabria', 'S', 'Provincia de Cantabria');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (14, 'Castellón', 'CS', 'Provincia de Castellón');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (15, 'Ciudad Real', 'CR', 'Provincia de Ciudad Real');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (16, 'Córdoba', 'CO', 'Provincia de Córdoba');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (17, 'Cuenca', 'CU', 'Provincia de Cuenca');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (18, 'Girona', 'GI', 'Provincia de Girona');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (19, 'Granada', 'GR', 'Provincia de Granada');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (20, 'Guadalajara', 'GU', 'Provincia de Guadalajara');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (21, 'Guipúzcoa', 'SS', 'Provincia de Guipúzcoa');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (22, 'Huelva', 'H', 'Provincia de Huelva');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (23, 'Huesca', 'HU', 'Provincia de Huesca');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (24, 'Jaén', 'J', 'Provincia de Jaén');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (25, 'La Coruña', 'C', 'Provincia de La Coruña');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (26, 'La Rioja', 'LO', 'Provincia de La Rioja');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (27, 'Las Palmas', 'GC', 'Provincia de Las Palmas');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (28, 'León', 'LE', 'Provincia de León');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (29, 'Lleida', 'L', 'Provincia de Lleida');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (30, 'Lugo', 'LU', 'Provincia de Lugo');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (31, 'Madrid', 'M', 'Provincia de Madrid');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (32, 'Málaga', 'MA', 'Provincia de Málaga');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (33, 'Murcia', 'MU', 'Provincia de Murcia');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (34, 'Navarra', 'NA', 'Provincia de Navarra');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (35, 'Ourense', 'OR', 'Provincia de Ourense');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (36, 'Palencia', 'P', 'Provincia de Palencia');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (37, 'Pontevedra', 'PO', 'Provincia de Pontevedra');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (38, 'Salamanca', 'SA', 'Provincia de Salamanca');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (39, 'Santa Cruz de Tenerife', 'TF', 'Provincia de Santa Cruz de Tenerife');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (40, 'Segovia', 'SG', 'Provincia de Segovia');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (41, 'Sevilla', 'SE', 'Provincia de Sevilla');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (42, 'Soria', 'SO', 'Provincia de Soria');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (43, 'Tarragona', 'T', 'Provincia de Tarragona');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (44, 'Teruel', 'TE', 'Provincia de Teruel');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (45, 'Toledo', 'TO', 'Provincia de Toledo');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (46, 'Valencia', 'V', 'Provincia de Valencia');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (47, 'Valladolid', 'VA', 'Provincia de Valladolid');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (48, 'Vizcaya', 'BI', 'Provincia de Vizcaya');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (49, 'Zamora', 'ZA', 'Provincia de Zamora');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (50, 'Zaragoza', 'Z', 'Provincia de Zaragoza');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (51, 'Ceuta', 'CE', 'Provincia de Ceuta');
INSERT INTO provincia (id, nombre, codigo, descripcion) VALUES (52, 'Melilla', 'ML', 'Provincia de Melilla');